version: "3"

services:
  lavalink:
    image: fredboat/lavalink:latest
    container_name: Lavalink
    restart: unless-stopped
    networks:
      - lavalink-net
    volumes:
      - ./Logs:/opt/Lavalink/logs:rw
      - ./Lavalink.yml:/opt/Lavalink/application.yml:ro
  bot:
    build: .
    container_name: OurGuardianBot
    restart: unless-stopped
    depends_on:
      - lavalink
    networks:
      - lavalink-net
    volumes:
      - ./Logs:/app/Logs:rw
      - ./appsettings.json:/app/appsettings.json:ro

networks:
  lavalink-net:
    driver: bridge
