version: "3"
services:
  lavalink:
    image: fredboat/lavalink:latest
    ports:
      - 2333:2333
    volumes:
      - ./Logs:/opt/Lavalink/logs:rw
  bot:
    image: moecore/ourguardianbot:latest
    volumes:
      - ./Logs:/app/Logs:rw
